name: flutter_sub_provider
description: Sane Provider-Provider dependencies with flutter_sub. A smart alternative to ProxyProvider.
version: 0.2.0
repository: https://github.com/clragon/flutter_sub_provider

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter_sub: ">=1.0.0 <2.0.0"
  provider: ">=6.0.0 <7.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
